-- =========================================
-- 001_create_schema
-- 「これ持ってる？」v0.1 基本DB
-- =========================================

create table public.households (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  created_at timestamptz not null default now()
);

create table public.household_items (
  id bigint generated by default as identity primary key,
  household_id uuid not null
    references public.households(id)
    on delete cascade,
  barcode text not null
    check (barcode ~ '^[0-9]{8,14}$'),
  registered_at timestamptz not null default now(),
  unique (household_id, barcode)
);

create table public.event_logs (
  id bigint generated by default as identity primary key,
  household_id uuid
    references public.households(id)
    on delete cascade,
  event_type text not null
    check (
      event_type in (
        'REGISTER',
        'CHECK_MATCH',
        'CHECK_NOT_FOUND',
        'SCAN_FAILED',
        'DELETE'
      )
    ),
  barcode text,
  result text,
  client_type text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index household_items_lookup_idx
  on public.household_items (household_id, barcode);

create index event_logs_household_time_idx
  on public.event_logs (household_id, created_at desc);

alter table public.households enable row level security;
alter table public.household_items enable row level security;
alter table public.event_logs enable row level security;
