-- =========================================
-- 003_create_share_check_api
-- 共有用トークン + 照合専用RPC
-- =========================================

create extension if not exists pgcrypto;

create table public.share_tokens (
  id bigint generated by default as identity primary key,
  household_id uuid not null
    references public.households(id)
    on delete cascade,
  token_hash text not null unique,
  permission text not null default 'CHECK'
    check (permission = 'CHECK'),
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

alter table public.share_tokens enable row level security;

revoke all on table public.households from anon, authenticated;
revoke all on table public.household_items from anon, authenticated;
revoke all on table public.event_logs from anon, authenticated;
revoke all on table public.share_tokens from anon, authenticated;

create or replace function public.check_household_barcode(
  p_token text,
  p_barcode text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_registered boolean;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'CHECK'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return false;
  end if;

  select exists (
    select 1
    from public.household_items hi
    where hi.household_id = v_household_id
      and hi.barcode = p_barcode
  )
  into v_registered;

  insert into public.event_logs (
    household_id,
    event_type,
    barcode,
    result
  )
  values (
    v_household_id,
    case
      when v_registered then 'CHECK_MATCH'
      else 'CHECK_NOT_FOUND'
    end,
    p_barcode,
    case
      when v_registered then 'matched'
      else 'not_found'
    end
  );

  return v_registered;
end;
$$;

revoke all on function public.check_household_barcode(text, text)
  from public;

grant execute on function public.check_household_barcode(text, text)
  to anon, authenticated;

-- 初回共有トークン発行
with raw as (
  select encode(gen_random_bytes(32), 'hex') as token
),
target as (
  select id
  from public.households
  where display_name = '新井家・試験'
  limit 1
),
saved as (
  insert into public.share_tokens (
    household_id,
    token_hash
  )
  select
    target.id,
    encode(digest(raw.token, 'sha256'), 'hex')
  from raw, target
  returning id
)
select raw.token
from raw, saved;
