-- =========================================
-- 006_shared_cart_foundation
-- 所有数量 + 共有買い物かご（購入予定レイヤー）の土台
-- 重複は「禁止」ではなく「警告」に使う
-- =========================================

-- 1) 所有物は1件/商品コードのまま、数量を持てるようにする
alter table public.household_items
  add column if not exists quantity integer not null default 1;

alter table public.household_items
  drop constraint if exists household_items_quantity_check;

alter table public.household_items
  add constraint household_items_quantity_check
  check (quantity >= 1);

-- 2) Aさん/Bさん/Cさん…の「これを買う予定」を重ねて持つ
--    同一 household_id + barcode を複数行許可する。
--    つまり重複してもDBでは弾かない。
create table if not exists public.purchase_plans (
  id bigint generated by default as identity primary key,
  household_id uuid not null
    references public.households(id)
    on delete cascade,
  barcode text not null
    check (barcode ~ '^[0-9]{8,14}$'),
  buyer_label text,
  quantity integer not null default 1
    check (quantity >= 1),
  status text not null default 'PLANNED'
    check (status in ('PLANNED', 'PURCHASED', 'CANCELLED')),
  visibility text not null default 'GIFT_SECRET'
    check (visibility in ('GIFT_SECRET', 'HOUSEHOLD_SHARED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists purchase_plans_lookup_idx
  on public.purchase_plans (household_id, barcode, status);

alter table public.purchase_plans enable row level security;

-- ブラウザからテーブルを直接触らせない。後続のRPC経由に限定する。
revoke all on table public.purchase_plans from anon, authenticated;

-- 3) 共有リンク + 商品コードから「家庭全体を真上から見た状態」を返す
--    誰が買う予定かは返さず、数量だけ返す。
create or replace function public.get_household_product_state(
  p_token text,
  p_barcode text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_owned_quantity integer := 0;
  v_planned_quantity integer := 0;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'CHECK'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object(
      'valid_token', false,
      'owned_quantity', 0,
      'planned_quantity', 0,
      'duplicate', false
    );
  end if;

  select coalesce(sum(hi.quantity), 0)::integer
    into v_owned_quantity
  from public.household_items hi
  where hi.household_id = v_household_id
    and hi.barcode = p_barcode;

  select coalesce(sum(pp.quantity), 0)::integer
    into v_planned_quantity
  from public.purchase_plans pp
  where pp.household_id = v_household_id
    and pp.barcode = p_barcode
    and pp.status = 'PLANNED';

  return jsonb_build_object(
    'valid_token', true,
    'owned_quantity', v_owned_quantity,
    'planned_quantity', v_planned_quantity,
    'duplicate', (v_owned_quantity + v_planned_quantity) > 0
  );
end;
$$;

revoke all on function public.get_household_product_state(text, text)
  from public;

grant execute on function public.get_household_product_state(text, text)
  to anon, authenticated;
