-- =========================================
-- 012_handoff_receive_flow
-- ゲストの「渡した」→ オーナーの「受け取った」確認で在庫加算
-- ゲストは在庫を直接変更せず、受け渡し事実だけを登録する。
-- =========================================

create table if not exists public.handoff_requests (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  barcode text not null check (barcode ~ '^[0-9]{8,14}$'),
  quantity integer not null default 1 check (quantity >= 1),
  sender_key text,
  sender_label text,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'RECEIVED', 'CANCELLED')),
  created_at timestamptz not null default now(),
  received_at timestamptz
);

create index if not exists handoff_requests_household_status_created_idx
  on public.handoff_requests (household_id, status, created_at desc);

alter table public.handoff_requests enable row level security;
revoke all on table public.handoff_requests from public, anon, authenticated;

-- 既存の購入予定を「誰の予定か」追えるようにする。
-- 過去データはNULLのままでよく、新規追加分からbuyer_keyを保存する。
alter table public.purchase_plans
  add column if not exists buyer_key text;

create index if not exists purchase_plans_buyer_lookup_idx
  on public.purchase_plans (household_id, barcode, buyer_key, status);

create or replace function public.add_purchase_plan(
  p_token text,
  p_barcode text,
  p_buyer_key text,
  p_buyer_label text default null,
  p_quantity integer default 1,
  p_visibility text default 'GIFT_SECRET'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_owned_quantity integer := 0;
  v_planned_quantity_before integer := 0;
  v_plan_id bigint;
begin
  if p_quantity is null or p_quantity < 1 then
    raise exception 'quantity must be >= 1';
  end if;

  if p_visibility not in ('GIFT_SECRET', 'HOUSEHOLD_SHARED') then
    raise exception 'invalid visibility';
  end if;

  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'SHOP'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  select coalesce(sum(hi.quantity), 0)::integer
    into v_owned_quantity
  from public.household_items hi
  where hi.household_id = v_household_id
    and hi.barcode = p_barcode;

  select coalesce(sum(pp.quantity), 0)::integer
    into v_planned_quantity_before
  from public.purchase_plans pp
  where pp.household_id = v_household_id
    and pp.barcode = p_barcode
    and pp.status = 'PLANNED';

  insert into public.purchase_plans (
    household_id,
    barcode,
    buyer_key,
    buyer_label,
    quantity,
    status,
    visibility
  )
  values (
    v_household_id,
    p_barcode,
    nullif(trim(p_buyer_key), ''),
    coalesce(nullif(trim(p_buyer_label), ''), '共有ユーザー'),
    p_quantity,
    'PLANNED',
    p_visibility
  )
  returning id into v_plan_id;

  return jsonb_build_object(
    'valid_token', true,
    'plan_id', v_plan_id,
    'owned_quantity', v_owned_quantity,
    'planned_quantity_before', v_planned_quantity_before,
    'planned_quantity_after', v_planned_quantity_before + p_quantity,
    'duplicate_before_add', (v_owned_quantity + v_planned_quantity_before) > 0,
    'buyer_key', p_buyer_key
  );
end;
$$;

revoke all on function public.add_purchase_plan(text, text, text, text, integer, text)
  from public;
grant execute on function public.add_purchase_plan(text, text, text, text, integer, text)
  to anon, authenticated;

create or replace function public.create_handoff_request(
  p_token text,
  p_barcode text,
  p_buyer_key text default null,
  p_sender_label text default null,
  p_quantity integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_request_id bigint;
  v_remaining integer;
  v_consumed integer := 0;
  v_plan record;
begin
  if p_barcode is null or p_barcode !~ '^[0-9]{8,14}$' then
    return jsonb_build_object(
      'valid_token', true,
      'valid_barcode', false,
      'valid_quantity', p_quantity is not null and p_quantity >= 1
    );
  end if;

  if p_quantity is null or p_quantity < 1 then
    return jsonb_build_object(
      'valid_token', true,
      'valid_barcode', true,
      'valid_quantity', false
    );
  end if;

  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'SHOP'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  insert into public.handoff_requests (
    household_id,
    barcode,
    quantity,
    sender_key,
    sender_label
  )
  values (
    v_household_id,
    p_barcode,
    p_quantity,
    nullif(trim(p_buyer_key), ''),
    coalesce(nullif(trim(p_sender_label), ''), 'ゲスト')
  )
  returning id into v_request_id;

  -- 同じゲストがこの本を購入予定に入れていた場合だけ、
  -- 渡した数量ぶんを購入予定から消費する。
  v_remaining := p_quantity;

  if nullif(trim(p_buyer_key), '') is not null then
    for v_plan in
      select pp.id, pp.quantity
      from public.purchase_plans pp
      where pp.household_id = v_household_id
        and pp.barcode = p_barcode
        and pp.buyer_key = p_buyer_key
        and pp.status = 'PLANNED'
      order by pp.created_at, pp.id
      for update
    loop
      exit when v_remaining <= 0;

      if v_plan.quantity <= v_remaining then
        update public.purchase_plans
        set status = 'PURCHASED',
            updated_at = now()
        where id = v_plan.id;

        v_remaining := v_remaining - v_plan.quantity;
        v_consumed := v_consumed + v_plan.quantity;
      else
        update public.purchase_plans
        set quantity = quantity - v_remaining,
            updated_at = now()
        where id = v_plan.id;

        v_consumed := v_consumed + v_remaining;
        v_remaining := 0;
      end if;
    end loop;
  end if;

  return jsonb_build_object(
    'valid_token', true,
    'valid_barcode', true,
    'valid_quantity', true,
    'handoff_id', v_request_id,
    'quantity', p_quantity,
    'planned_quantity_consumed', v_consumed,
    'status', 'PENDING'
  );
end;
$$;

revoke all on function public.create_handoff_request(text, text, text, text, integer)
  from public;
grant execute on function public.create_handoff_request(text, text, text, text, integer)
  to anon, authenticated;

create or replace function public.get_pending_handoffs(
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_items jsonb;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'OWNER'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object(
      'valid_token', false,
      'items', '[]'::jsonb
    );
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', hr.id,
        'barcode', hr.barcode,
        'quantity', hr.quantity,
        'sender_label', hr.sender_label,
        'created_at', hr.created_at
      )
      order by hr.created_at
    ),
    '[]'::jsonb
  )
  into v_items
  from public.handoff_requests hr
  where hr.household_id = v_household_id
    and hr.status = 'PENDING';

  return jsonb_build_object(
    'valid_token', true,
    'items', v_items
  );
end;
$$;

revoke all on function public.get_pending_handoffs(text) from public;
grant execute on function public.get_pending_handoffs(text) to anon, authenticated;

create or replace function public.accept_handoff_request(
  p_token text,
  p_handoff_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_request public.handoff_requests%rowtype;
  v_item_id bigint;
  v_quantity_before integer := 0;
  v_quantity_after integer := 0;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'OWNER'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  perform 1
  from public.households h
  where h.id = v_household_id
  for update;

  select hr.*
    into v_request
  from public.handoff_requests hr
  where hr.id = p_handoff_id
    and hr.household_id = v_household_id
  for update;

  if v_request.id is null then
    return jsonb_build_object(
      'valid_token', true,
      'request_found', false,
      'accepted', false
    );
  end if;

  if v_request.status <> 'PENDING' then
    return jsonb_build_object(
      'valid_token', true,
      'request_found', true,
      'accepted', false,
      'status', v_request.status
    );
  end if;

  select hi.id, hi.quantity
    into v_item_id, v_quantity_before
  from public.household_items hi
  where hi.household_id = v_household_id
    and hi.barcode = v_request.barcode
  limit 1;

  v_quantity_before := coalesce(v_quantity_before, 0);

  if v_item_id is null then
    insert into public.household_items (
      household_id,
      barcode,
      quantity
    )
    values (
      v_household_id,
      v_request.barcode,
      v_request.quantity
    )
    returning id, quantity into v_item_id, v_quantity_after;
  else
    update public.household_items
    set quantity = quantity + v_request.quantity
    where id = v_item_id
    returning quantity into v_quantity_after;
  end if;

  update public.handoff_requests
  set status = 'RECEIVED',
      received_at = now()
  where id = v_request.id;

  return jsonb_build_object(
    'valid_token', true,
    'request_found', true,
    'accepted', true,
    'handoff_id', v_request.id,
    'barcode', v_request.barcode,
    'added_quantity', v_request.quantity,
    'quantity_before', v_quantity_before,
    'quantity', v_quantity_after,
    'status', 'RECEIVED'
  );
end;
$$;

revoke all on function public.accept_handoff_request(text, bigint) from public;
grant execute on function public.accept_handoff_request(text, bigint) to anon, authenticated;
