-- =========================================
-- 013_guest_name_and_item_provenance
-- ゲストの呼ばれ方を購入予定・受け渡しへ残し、
-- 受取確定後も「誰から来た本か」を在庫の来歴として保持する。
-- =========================================

alter table public.handoff_requests
  add column if not exists purchaser_label text;

create table if not exists public.item_origins (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  barcode text not null check (barcode ~ '^[0-9]{8,14}$'),
  quantity integer not null default 1 check (quantity >= 1),
  purchaser_label text,
  giver_label text,
  acquisition_type text not null default 'HANDOFF'
    check (acquisition_type in ('HANDOFF', 'OWNER_REGISTERED')),
  handoff_id bigint unique references public.handoff_requests(id) on delete set null,
  acquired_at timestamptz not null default now()
);

create index if not exists item_origins_household_barcode_idx
  on public.item_origins (household_id, barcode, acquired_at desc);

alter table public.item_origins enable row level security;
revoke all on table public.item_origins from public, anon, authenticated;

create or replace function public.create_handoff_request(
  p_token text,
  p_barcode text,
  p_buyer_key text default null,
  p_sender_label text default null,
  p_quantity integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_request_id bigint;
  v_remaining integer;
  v_consumed integer := 0;
  v_plan record;
  v_sender_label text;
  v_purchaser_label text;
begin
  if p_barcode is null or p_barcode !~ '^[0-9]{8,14}$' then
    return jsonb_build_object(
      'valid_token', true,
      'valid_barcode', false,
      'valid_quantity', p_quantity is not null and p_quantity >= 1
    );
  end if;

  if p_quantity is null or p_quantity < 1 then
    return jsonb_build_object(
      'valid_token', true,
      'valid_barcode', true,
      'valid_quantity', false
    );
  end if;

  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'SHOP'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  v_sender_label := nullif(left(trim(coalesce(p_sender_label, '')), 40), '');

  if nullif(trim(coalesce(p_buyer_key, '')), '') is not null then
    select nullif(left(trim(coalesce(pp.buyer_label, '')), 40), '')
      into v_purchaser_label
    from public.purchase_plans pp
    where pp.household_id = v_household_id
      and pp.barcode = p_barcode
      and pp.buyer_key = p_buyer_key
      and pp.status = 'PLANNED'
    order by pp.created_at desc, pp.id desc
    limit 1;
  end if;

  v_purchaser_label := coalesce(v_purchaser_label, v_sender_label);

  insert into public.handoff_requests (
    household_id,
    barcode,
    quantity,
    sender_key,
    sender_label,
    purchaser_label
  )
  values (
    v_household_id,
    p_barcode,
    p_quantity,
    nullif(trim(p_buyer_key), ''),
    coalesce(v_sender_label, 'ゲスト'),
    coalesce(v_purchaser_label, v_sender_label, 'ゲスト')
  )
  returning id into v_request_id;

  -- 同じゲストの購入予定だけを、渡した数量ぶん消費する。
  v_remaining := p_quantity;

  if nullif(trim(coalesce(p_buyer_key, '')), '') is not null then
    for v_plan in
      select pp.id, pp.quantity
      from public.purchase_plans pp
      where pp.household_id = v_household_id
        and pp.barcode = p_barcode
        and pp.buyer_key = p_buyer_key
        and pp.status = 'PLANNED'
      order by pp.created_at, pp.id
      for update
    loop
      exit when v_remaining <= 0;

      if v_plan.quantity <= v_remaining then
        update public.purchase_plans
        set status = 'PURCHASED',
            updated_at = now()
        where id = v_plan.id;

        v_remaining := v_remaining - v_plan.quantity;
        v_consumed := v_consumed + v_plan.quantity;
      else
        update public.purchase_plans
        set quantity = quantity - v_remaining,
            updated_at = now()
        where id = v_plan.id;

        v_consumed := v_consumed + v_remaining;
        v_remaining := 0;
      end if;
    end loop;
  end if;

  return jsonb_build_object(
    'valid_token', true,
    'valid_barcode', true,
    'valid_quantity', true,
    'handoff_id', v_request_id,
    'quantity', p_quantity,
    'sender_label', coalesce(v_sender_label, 'ゲスト'),
    'purchaser_label', coalesce(v_purchaser_label, v_sender_label, 'ゲスト'),
    'planned_quantity_consumed', v_consumed,
    'status', 'PENDING'
  );
end;
$$;

revoke all on function public.create_handoff_request(text, text, text, text, integer)
  from public;
grant execute on function public.create_handoff_request(text, text, text, text, integer)
  to anon, authenticated;

create or replace function public.get_pending_handoffs(
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_items jsonb;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'OWNER'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object(
      'valid_token', false,
      'items', '[]'::jsonb
    );
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', hr.id,
        'barcode', hr.barcode,
        'quantity', hr.quantity,
        'sender_label', hr.sender_label,
        'purchaser_label', hr.purchaser_label,
        'created_at', hr.created_at
      )
      order by hr.created_at
    ),
    '[]'::jsonb
  )
  into v_items
  from public.handoff_requests hr
  where hr.household_id = v_household_id
    and hr.status = 'PENDING';

  return jsonb_build_object(
    'valid_token', true,
    'items', v_items
  );
end;
$$;

revoke all on function public.get_pending_handoffs(text) from public;
grant execute on function public.get_pending_handoffs(text) to anon, authenticated;

create or replace function public.accept_handoff_request(
  p_token text,
  p_handoff_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_request public.handoff_requests%rowtype;
  v_item_id bigint;
  v_quantity_before integer := 0;
  v_quantity_after integer := 0;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'OWNER'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  perform 1
  from public.households h
  where h.id = v_household_id
  for update;

  select hr.*
    into v_request
  from public.handoff_requests hr
  where hr.id = p_handoff_id
    and hr.household_id = v_household_id
  for update;

  if v_request.id is null then
    return jsonb_build_object(
      'valid_token', true,
      'request_found', false,
      'accepted', false
    );
  end if;

  if v_request.status <> 'PENDING' then
    return jsonb_build_object(
      'valid_token', true,
      'request_found', true,
      'accepted', false,
      'status', v_request.status
    );
  end if;

  select hi.id, hi.quantity
    into v_item_id, v_quantity_before
  from public.household_items hi
  where hi.household_id = v_household_id
    and hi.barcode = v_request.barcode
  limit 1;

  v_quantity_before := coalesce(v_quantity_before, 0);

  if v_item_id is null then
    insert into public.household_items (
      household_id,
      barcode,
      quantity
    )
    values (
      v_household_id,
      v_request.barcode,
      v_request.quantity
    )
    returning id, quantity into v_item_id, v_quantity_after;
  else
    update public.household_items
    set quantity = quantity + v_request.quantity
    where id = v_item_id
    returning quantity into v_quantity_after;
  end if;

  update public.handoff_requests
  set status = 'RECEIVED',
      received_at = now()
  where id = v_request.id;

  insert into public.item_origins (
    household_id,
    barcode,
    quantity,
    purchaser_label,
    giver_label,
    acquisition_type,
    handoff_id,
    acquired_at
  )
  values (
    v_household_id,
    v_request.barcode,
    v_request.quantity,
    nullif(left(trim(coalesce(v_request.purchaser_label, '')), 40), ''),
    nullif(left(trim(coalesce(v_request.sender_label, '')), 40), ''),
    'HANDOFF',
    v_request.id,
    now()
  )
  on conflict (handoff_id) do nothing;

  return jsonb_build_object(
    'valid_token', true,
    'request_found', true,
    'accepted', true,
    'handoff_id', v_request.id,
    'barcode', v_request.barcode,
    'added_quantity', v_request.quantity,
    'quantity_before', v_quantity_before,
    'quantity', v_quantity_after,
    'purchaser_label', v_request.purchaser_label,
    'giver_label', v_request.sender_label,
    'status', 'RECEIVED'
  );
end;
$$;

revoke all on function public.accept_handoff_request(text, bigint) from public;
grant execute on function public.accept_handoff_request(text, bigint) to anon, authenticated;

create or replace function public.get_household_owned_items(
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_items jsonb;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission in ('CHECK', 'SHOP', 'OWNER')
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object(
      'valid_token', false,
      'items', '[]'::jsonb
    );
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'barcode', hi.barcode,
        'quantity', hi.quantity,
        'registered_at', hi.registered_at,
        'origins', coalesce(origin_rows.origins, '[]'::jsonb)
      )
      order by hi.registered_at desc
    ),
    '[]'::jsonb
  )
  into v_items
  from public.household_items hi
  left join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'quantity', io.quantity,
        'purchaser_label', io.purchaser_label,
        'giver_label', io.giver_label,
        'acquisition_type', io.acquisition_type,
        'acquired_at', io.acquired_at
      )
      order by io.acquired_at desc, io.id desc
    ) as origins
    from public.item_origins io
    where io.household_id = hi.household_id
      and io.barcode = hi.barcode
  ) origin_rows on true
  where hi.household_id = v_household_id;

  return jsonb_build_object(
    'valid_token', true,
    'items', v_items
  );
end;
$$;

revoke all on function public.get_household_owned_items(text) from public;
grant execute on function public.get_household_owned_items(text) to anon, authenticated;
