-- =========================================
-- 015_handoff_conflict_and_cancel
-- 受け取り待ちとオーナー手動登録の二重計上を防ぎ、
-- 「渡した」の取消を安全に扱う。
-- =========================================

create table if not exists public.handoff_plan_consumptions (
  id bigint generated by default as identity primary key,
  handoff_id bigint not null references public.handoff_requests(id) on delete cascade,
  purchase_plan_id bigint references public.purchase_plans(id) on delete set null,
  consumed_quantity integer not null check (consumed_quantity >= 1),
  consumed_whole boolean not null default false,
  created_at timestamptz not null default now(),
  unique (handoff_id, purchase_plan_id)
);

alter table public.handoff_plan_consumptions enable row level security;
revoke all on table public.handoff_plan_consumptions from public, anon, authenticated;

-- 「渡した」登録時に、どの購入予定を何冊ぶん消費したかも記録する。
create or replace function public.create_handoff_request(
  p_token text,
  p_barcode text,
  p_buyer_key text default null,
  p_sender_label text default null,
  p_quantity integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_request_id bigint;
  v_remaining integer;
  v_consumed integer := 0;
  v_take integer := 0;
  v_plan record;
  v_sender_label text;
  v_purchaser_label text;
begin
  if p_barcode is null or p_barcode !~ '^[0-9]{8,14}$' then
    return jsonb_build_object(
      'valid_token', true,
      'valid_barcode', false,
      'valid_quantity', p_quantity is not null and p_quantity >= 1
    );
  end if;

  if p_quantity is null or p_quantity < 1 then
    return jsonb_build_object(
      'valid_token', true,
      'valid_barcode', true,
      'valid_quantity', false
    );
  end if;

  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'SHOP'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  perform 1
  from public.households h
  where h.id = v_household_id
  for update;

  v_sender_label := nullif(left(trim(coalesce(p_sender_label, '')), 40), '');

  if nullif(trim(coalesce(p_buyer_key, '')), '') is not null then
    select nullif(left(trim(coalesce(pp.buyer_label, '')), 40), '')
      into v_purchaser_label
    from public.purchase_plans pp
    where pp.household_id = v_household_id
      and pp.barcode = p_barcode
      and pp.buyer_key = p_buyer_key
      and pp.status = 'PLANNED'
    order by pp.created_at desc, pp.id desc
    limit 1;
  end if;

  v_purchaser_label := coalesce(v_purchaser_label, v_sender_label);

  insert into public.handoff_requests (
    household_id,
    barcode,
    quantity,
    sender_key,
    sender_label,
    purchaser_label
  )
  values (
    v_household_id,
    p_barcode,
    p_quantity,
    nullif(trim(p_buyer_key), ''),
    coalesce(v_sender_label, 'ゲスト'),
    coalesce(v_purchaser_label, v_sender_label, 'ゲスト')
  )
  returning id into v_request_id;

  v_remaining := p_quantity;

  if nullif(trim(coalesce(p_buyer_key, '')), '') is not null then
    for v_plan in
      select pp.id, pp.quantity
      from public.purchase_plans pp
      where pp.household_id = v_household_id
        and pp.barcode = p_barcode
        and pp.buyer_key = p_buyer_key
        and pp.status = 'PLANNED'
      order by pp.created_at, pp.id
      for update
    loop
      exit when v_remaining <= 0;
      v_take := least(v_plan.quantity, v_remaining);

      insert into public.handoff_plan_consumptions (
        handoff_id,
        purchase_plan_id,
        consumed_quantity,
        consumed_whole
      )
      values (
        v_request_id,
        v_plan.id,
        v_take,
        v_take = v_plan.quantity
      );

      if v_take = v_plan.quantity then
        update public.purchase_plans
        set status = 'PURCHASED',
            updated_at = now()
        where id = v_plan.id;
      else
        update public.purchase_plans
        set quantity = quantity - v_take,
            updated_at = now()
        where id = v_plan.id;
      end if;

      v_remaining := v_remaining - v_take;
      v_consumed := v_consumed + v_take;
    end loop;
  end if;

  return jsonb_build_object(
    'valid_token', true,
    'valid_barcode', true,
    'valid_quantity', true,
    'handoff_id', v_request_id,
    'quantity', p_quantity,
    'sender_label', coalesce(v_sender_label, 'ゲスト'),
    'purchaser_label', coalesce(v_purchaser_label, v_sender_label, 'ゲスト'),
    'planned_quantity_consumed', v_consumed,
    'status', 'PENDING'
  );
end;
$$;

revoke all on function public.create_handoff_request(text, text, text, text, integer) from public;
grant execute on function public.create_handoff_request(text, text, text, text, integer) to anon, authenticated;

-- オーナーの読取時に、同じ本の受け取り待ちも返す。
create or replace function public.get_owner_item_state(
  p_token text,
  p_barcode text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_quantity integer := 0;
  v_pending_quantity integer := 0;
  v_pending jsonb := '[]'::jsonb;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'OWNER'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  if p_barcode is null or p_barcode !~ '^[0-9]{8,14}$' then
    return jsonb_build_object(
      'valid_token', true,
      'valid_barcode', false,
      'exists', false,
      'quantity', 0,
      'pending_handoff_quantity', 0,
      'pending_handoffs', '[]'::jsonb
    );
  end if;

  select coalesce(hi.quantity, 0)
    into v_quantity
  from public.household_items hi
  where hi.household_id = v_household_id
    and hi.barcode = p_barcode
  limit 1;

  v_quantity := coalesce(v_quantity, 0);

  select
    coalesce(sum(hr.quantity), 0)::integer,
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', hr.id,
          'quantity', hr.quantity,
          'sender_label', hr.sender_label,
          'purchaser_label', hr.purchaser_label,
          'created_at', hr.created_at
        )
        order by hr.created_at, hr.id
      ),
      '[]'::jsonb
    )
    into v_pending_quantity, v_pending
  from public.handoff_requests hr
  where hr.household_id = v_household_id
    and hr.barcode = p_barcode
    and hr.status = 'PENDING';

  return jsonb_build_object(
    'valid_token', true,
    'valid_barcode', true,
    'exists', v_quantity > 0,
    'quantity', v_quantity,
    'pending_handoff_quantity', v_pending_quantity,
    'pending_handoffs', v_pending
  );
end;
$$;

revoke all on function public.get_owner_item_state(text, text) from public;
grant execute on function public.get_owner_item_state(text, text) to anon, authenticated;

-- 受け取り待ち一覧には、同じ本を現在何冊持っているかも添える。
create or replace function public.get_pending_handoffs(
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_items jsonb;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'OWNER'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false, 'items', '[]'::jsonb);
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', hr.id,
        'barcode', hr.barcode,
        'quantity', hr.quantity,
        'sender_label', hr.sender_label,
        'purchaser_label', hr.purchaser_label,
        'created_at', hr.created_at,
        'owned_quantity', coalesce(hi.quantity, 0)
      )
      order by hr.created_at, hr.id
    ),
    '[]'::jsonb
  )
  into v_items
  from public.handoff_requests hr
  left join public.household_items hi
    on hi.household_id = hr.household_id
   and hi.barcode = hr.barcode
  where hr.household_id = v_household_id
    and hr.status = 'PENDING';

  return jsonb_build_object('valid_token', true, 'items', v_items);
end;
$$;

revoke all on function public.get_pending_handoffs(text) from public;
grant execute on function public.get_pending_handoffs(text) to anon, authenticated;

-- すでに同じ受け取り分を手動登録済みなら、在庫を増やさず受取完了だけ行う。
create or replace function public.reconcile_handoff_request(
  p_token text,
  p_handoff_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_request public.handoff_requests%rowtype;
  v_owned_quantity integer := 0;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'OWNER'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  perform 1
  from public.households h
  where h.id = v_household_id
  for update;

  select hr.*
    into v_request
  from public.handoff_requests hr
  where hr.id = p_handoff_id
    and hr.household_id = v_household_id
  for update;

  if v_request.id is null then
    return jsonb_build_object('valid_token', true, 'request_found', false, 'reconciled', false);
  end if;

  if v_request.status <> 'PENDING' then
    return jsonb_build_object(
      'valid_token', true,
      'request_found', true,
      'reconciled', false,
      'status', v_request.status
    );
  end if;

  select coalesce(hi.quantity, 0)
    into v_owned_quantity
  from public.household_items hi
  where hi.household_id = v_household_id
    and hi.barcode = v_request.barcode
  limit 1;

  v_owned_quantity := coalesce(v_owned_quantity, 0);

  if v_owned_quantity < v_request.quantity then
    return jsonb_build_object(
      'valid_token', true,
      'request_found', true,
      'reconciled', false,
      'has_enough_owned', false,
      'owned_quantity', v_owned_quantity,
      'handoff_quantity', v_request.quantity
    );
  end if;

  update public.handoff_requests
  set status = 'RECEIVED',
      received_at = now()
  where id = v_request.id;

  insert into public.item_origins (
    household_id,
    barcode,
    quantity,
    purchaser_label,
    giver_label,
    acquisition_type,
    handoff_id,
    acquired_at
  )
  values (
    v_household_id,
    v_request.barcode,
    v_request.quantity,
    nullif(left(trim(coalesce(v_request.purchaser_label, '')), 40), ''),
    nullif(left(trim(coalesce(v_request.sender_label, '')), 40), ''),
    'HANDOFF',
    v_request.id,
    now()
  )
  on conflict (handoff_id) do nothing;

  return jsonb_build_object(
    'valid_token', true,
    'request_found', true,
    'reconciled', true,
    'handoff_id', v_request.id,
    'barcode', v_request.barcode,
    'added_quantity', 0,
    'quantity', v_owned_quantity,
    'status', 'RECEIVED'
  );
end;
$$;

revoke all on function public.reconcile_handoff_request(text, bigint) from public;
grant execute on function public.reconcile_handoff_request(text, bigint) to anon, authenticated;

-- ゲスト本人が作った受け取り待ちだけ取得する。
create or replace function public.get_my_pending_handoffs(
  p_token text,
  p_buyer_key text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_items jsonb;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'SHOP'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false, 'items', '[]'::jsonb);
  end if;

  if nullif(trim(coalesce(p_buyer_key, '')), '') is null then
    return jsonb_build_object('valid_token', true, 'items', '[]'::jsonb);
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', hr.id,
        'barcode', hr.barcode,
        'quantity', hr.quantity,
        'sender_label', hr.sender_label,
        'created_at', hr.created_at
      )
      order by hr.created_at desc, hr.id desc
    ),
    '[]'::jsonb
  )
  into v_items
  from public.handoff_requests hr
  where hr.household_id = v_household_id
    and hr.sender_key = p_buyer_key
    and hr.status = 'PENDING';

  return jsonb_build_object('valid_token', true, 'items', v_items);
end;
$$;

revoke all on function public.get_my_pending_handoffs(text, text) from public;
grant execute on function public.get_my_pending_handoffs(text, text) to anon, authenticated;

-- 「渡した」を取り消し、今回消費した購入予定だけを元へ戻す。
create or replace function public.cancel_my_handoff_request(
  p_token text,
  p_handoff_id bigint,
  p_buyer_key text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_request public.handoff_requests%rowtype;
  v_link record;
  v_plan_status text;
  v_restored integer := 0;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'SHOP'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  perform 1 from public.households h where h.id = v_household_id for update;

  select hr.*
    into v_request
  from public.handoff_requests hr
  where hr.id = p_handoff_id
    and hr.household_id = v_household_id
    and hr.sender_key = p_buyer_key
  for update;

  if v_request.id is null then
    return jsonb_build_object('valid_token', true, 'request_found', false, 'cancelled', false);
  end if;

  if v_request.status <> 'PENDING' then
    return jsonb_build_object(
      'valid_token', true,
      'request_found', true,
      'cancelled', false,
      'status', v_request.status
    );
  end if;

  for v_link in
    select hpc.purchase_plan_id, hpc.consumed_quantity, hpc.consumed_whole
    from public.handoff_plan_consumptions hpc
    where hpc.handoff_id = v_request.id
    order by hpc.id
  loop
    if v_link.purchase_plan_id is null then
      continue;
    end if;

    select pp.status
      into v_plan_status
    from public.purchase_plans pp
    where pp.id = v_link.purchase_plan_id
      and pp.household_id = v_household_id
    for update;

    if v_link.consumed_whole and v_plan_status = 'PURCHASED' then
      update public.purchase_plans
      set status = 'PLANNED',
          updated_at = now()
      where id = v_link.purchase_plan_id;
      v_restored := v_restored + v_link.consumed_quantity;
    elsif not v_link.consumed_whole and v_plan_status = 'PLANNED' then
      update public.purchase_plans
      set quantity = quantity + v_link.consumed_quantity,
          updated_at = now()
      where id = v_link.purchase_plan_id;
      v_restored := v_restored + v_link.consumed_quantity;
    end if;
  end loop;

  update public.handoff_requests
  set status = 'CANCELLED'
  where id = v_request.id;

  return jsonb_build_object(
    'valid_token', true,
    'request_found', true,
    'cancelled', true,
    'handoff_id', v_request.id,
    'restored_planned_quantity', v_restored,
    'status', 'CANCELLED'
  );
end;
$$;

revoke all on function public.cancel_my_handoff_request(text, bigint, text) from public;
grant execute on function public.cancel_my_handoff_request(text, bigint, text) to anon, authenticated;

-- オーナーも未受取の依頼を取り消せる。購入予定の復元規則は同じ。
create or replace function public.cancel_owner_handoff_request(
  p_token text,
  p_handoff_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_request public.handoff_requests%rowtype;
  v_link record;
  v_plan_status text;
  v_restored integer := 0;
begin
  select st.household_id
    into v_household_id
  from public.share_tokens st
  where st.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
    and st.permission = 'OWNER'
    and st.revoked_at is null
  limit 1;

  if v_household_id is null then
    return jsonb_build_object('valid_token', false);
  end if;

  perform 1 from public.households h where h.id = v_household_id for update;

  select hr.*
    into v_request
  from public.handoff_requests hr
  where hr.id = p_handoff_id
    and hr.household_id = v_household_id
  for update;

  if v_request.id is null then
    return jsonb_build_object('valid_token', true, 'request_found', false, 'cancelled', false);
  end if;

  if v_request.status <> 'PENDING' then
    return jsonb_build_object(
      'valid_token', true,
      'request_found', true,
      'cancelled', false,
      'status', v_request.status
    );
  end if;

  for v_link in
    select hpc.purchase_plan_id, hpc.consumed_quantity, hpc.consumed_whole
    from public.handoff_plan_consumptions hpc
    where hpc.handoff_id = v_request.id
    order by hpc.id
  loop
    if v_link.purchase_plan_id is null then
      continue;
    end if;

    select pp.status
      into v_plan_status
    from public.purchase_plans pp
    where pp.id = v_link.purchase_plan_id
      and pp.household_id = v_household_id
    for update;

    if v_link.consumed_whole and v_plan_status = 'PURCHASED' then
      update public.purchase_plans
      set status = 'PLANNED',
          updated_at = now()
      where id = v_link.purchase_plan_id;
      v_restored := v_restored + v_link.consumed_quantity;
    elsif not v_link.consumed_whole and v_plan_status = 'PLANNED' then
      update public.purchase_plans
      set quantity = quantity + v_link.consumed_quantity,
          updated_at = now()
      where id = v_link.purchase_plan_id;
      v_restored := v_restored + v_link.consumed_quantity;
    end if;
  end loop;

  update public.handoff_requests
  set status = 'CANCELLED'
  where id = v_request.id;

  return jsonb_build_object(
    'valid_token', true,
    'request_found', true,
    'cancelled', true,
    'handoff_id', v_request.id,
    'restored_planned_quantity', v_restored,
    'status', 'CANCELLED'
  );
end;
$$;

revoke all on function public.cancel_owner_handoff_request(text, bigint) from public;
grant execute on function public.cancel_owner_handoff_request(text, bigint) to anon, authenticated;
